export const DAY_SELECTION_GET_DAYS = 'DAY_SELECTION_LOADING';
export const DAY_SELECTION_GET_DAYS_SUCCESS = 'DAY_SELECTION_GET_DAYS_SUCCESS';
export const DAY_SELECTION_GET_DAYS_FAILED = 'DAY_SELECTION_GET_DAYS_FAILED';
